name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install notcurses
        run: brew install notcurses
      - name: Build
        run: swift build
